CREATE TABLE DEPARTMENT(
	DEPARTMENTID SERIAL NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (DEPARTMENTID)
);

CREATE TABLE COUNTRY(
	COUNTRYID SERIAL NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (COUNTRYID)
);

CREATE TABLE CITY(
	CITYID SERIAL NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (CITYID),
	COUNTRYID INT REFERENCES COUNTRY(COUNTRYID)
);

CREATE TABLE ADDRESS(
	ADDRESSID SERIAL NOT NULL,
	LINE1 VARCHAR(50) NOT NULL,
	LINE2 VARCHAR(50),
	PRIMARY KEY (ADDRESSID),
	CITYID INT REFERENCES CITY(CITYID)
);

CREATE TABLE BRANCHOFFICE(
	BRANCHID SERIAL NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (BRANCHID),
	ADDRESSID INT REFERENCES ADDRESS(ADDRESSID)
);

CREATE TABLE POSITION(
	POSITIONID SERIAL NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (POSITIONID)
);

CREATE TABLE EMPLOYEE(
	EMPLOYEEID SERIAL NOT NULL,
	FULLNAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (EMPLOYEEID),
	BRANCHID INT REFERENCES BRANCHOFFICE(BRANCHID),
	DEPARTMENTID INT REFERENCES DEPARTMENT(DEPARTMENTID),
	POSITIONID INT REFERENCES POSITION(POSITIONID),
	ADDRESSID INT REFERENCES ADDRESS(ADDRESSID),
	SUPERVISORID INT REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE EMPLOYEEAUDIT(
	EMPLOYEEID INT,
	FULLNAME VARCHAR(100),
	BRANCHOFFICE VARCHAR(50),
	DEPARTMENT VARCHAR(30),
	SUPERVISOR VARCHAR(100),
	POSITION VARCHAR(30),
	ADDRESS VARCHAR(50),
	CITY VARCHAR(30),
	COUNTRY VARCHAR(30),
	EVENT VARCHAR(30),
	REGISTEREDAT TIMESTAMP
);