/**
* Persistencia tabla DEPARTMENT
*/
INSERT INTO DEPARTMENT (NAME) VALUES ('Department One');
INSERT INTO DEPARTMENT (NAME) VALUES ('Department Two');
INSERT INTO DEPARTMENT (NAME) VALUES ('Department Three');
INSERT INTO DEPARTMENT (NAME) VALUES ('Department Four');
INSERT INTO DEPARTMENT (NAME) VALUES ('Department Five');

/**
* Persistencia tabla COUNTRY
*/
INSERT INTO COUNTRY (NAME) VALUES ('Country One');
INSERT INTO COUNTRY (NAME) VALUES ('Country Two');
INSERT INTO COUNTRY (NAME) VALUES ('Country Three');
INSERT INTO COUNTRY (NAME) VALUES ('Country Four');
INSERT INTO COUNTRY (NAME) VALUES ('Country Five');

/**
* Persistencia tabla CITY
*/
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City One', 1);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Two', 1);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Three', 2);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Four', 2);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Five', 3);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Six', 3);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Seven', 4);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Eight', 4);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Nine', 5);
INSERT INTO CITY (NAME, COUNTRYID) VALUES ('City Ten', 5);

/**
* Persistencia tabla ADDRESS
*/
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address One', NULL, 1);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Two', 1);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Three', NULL, 2);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Four', 2);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Five', NULL, 3);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Six', 3);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Seven', NULL, 4);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Eight', 4);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Nine', NULL, 5);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Ten', 5);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Eleven', NULL, 6);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Twelve', 6);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Thirteen', NULL, 7);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Fourteen', 7);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Fifteen', NULL, 8);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'Sixteen', 8);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address Seventeen', NULL, 9);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'eighteen', 9);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address nineteen', NULL, 10);
INSERT INTO ADDRESS (LINE1, LINE2, CITYID) VALUES ('Address', 'twenty', 10);

SELECT * FROM ADDRESS;

/**
* Persistencia tabla BRANCHOFFICE
*/
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch One', 1);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Two', 2);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Three', 3);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Four', 4);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Five', 5);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Six', 6);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Seven', 7);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Eight', 8);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Nine', 9);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Ten', 10);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Eleven', 11);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Twelve', 12);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Thirteen', 13);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Fourteen', 14);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Fifteen', 15);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Sixteen', 16);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Seventeen', 17);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Eighteen', 18);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Nineteen', 19);
INSERT INTO BRANCHOFFICE (NAME, ADDRESSID) VALUES ('Branch Twenty', 20);

SELECT * FROM BRANCHOFFICE;

/**
* Persistencia tabla POSITION
*/

INSERT INTO POSITION (NAME) VALUES ('Position One');
INSERT INTO POSITION (NAME) VALUES ('Position Two');
INSERT INTO POSITION (NAME) VALUES ('Position Three');
INSERT INTO POSITION (NAME) VALUES ('Position Four');
INSERT INTO POSITION (NAME) VALUES ('Position Five');

SELECT * FROM POSITION;

/**
* Persistencia tabla EMPLOYEE
*/
